language: node_js
node_js:
  - 8
sudo: false
install:
- npm install
jobs:
  include:
    - stage: Tests
      script: npm run test
    - stage: Webpack Release
      script: npm run webpack
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: out
        target_branch: webpack
        name: Travis Webpack Deploy
        on: 
          branch: stable
    - stage: Docs Release
      script: npm run docs
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: out
        target_branch: gh-pages
        name: Travis Docs Deploy
        on: 
          branch: stable
    - stage: NPM Deploy
      deploy:
        provider: npm
        email: "ADD EMAIL ADDRESS HERE"
        api_key: "ADD AUTH TOKEN HERE"
        on:
          tags: true
          branch: stable
branches:
  except:
    - webpack
    - gh-pages
cache:
  directories:
    - node_modules
